### ISSUE TITLE
gdImageStringFT doesn't progress by the correct distance in y direction between characters

### ISSUE THREAD

**Issue by lnw** [libgd/libgd#887]
When writing a string with gdImagestringFT, one character is displaced relative to the previous character in x direction by the correct amount but by a wrong (but not always zero) amount in y direction. As a result one can correctly write horizontal strings, but writing vertical strings leads to all characters being printed in the same place (and diagonal strings have partially overlapping characters).

I have reproduced this issue (apart from my own project) with the gdimagestringft_bbox.c test from this project (but using vera.ttf that I have successfully used previously.)

Running this test (but ignoring the wrong bb stemming from a different font) I get:
![gdtest](https://github.com/user-attachments/assets/77bf60f4-ef18-4c89-82b9-e02861536f2e)

The libgd version is 2.3.3, as shipped by Debian testing, used from c++.

**Comment by cmb69** [comment]
Hmm, is this perhaps a font related issue? Or has this only been [fixed in PHP's bundled libgd](https://github.com/php/php-src/pull/1845)?

**Comment by lnw** [comment]
I'd say this is probably not an issue with the font file used.  I can reproduce this with an arial.ttf and vera.ttf.  I have used both files for several years without that issue and haven't changed how I call gdImageStringFT recently.  The only change is the versions of libraries that I use.

I'm not entirely sure this is a libgd issue either -- maybe dependent libraries such as libfreetype are to blame, but I don't know enough to say if that is plausible.  For what it's worth, I tried libfreetype 2.12.1 and 2.13.2 (as shipped by Debian testing) and the issue occurs with both.

**Comment by cmb69** [comment]
Ah, that might be an issue with libraqm (which is optionally supported as of libgd 2.3.0); see https://github.com/libgd/libgd/pull/196.

**Comment by lnw** [comment]
Indeed, downgrading libraqm from 0.10.1 to 0.7.0 solves my issue.  So I'm closing this issue. Thank you for your help, @cmb69 !

**Comment by cmb69** [comment]
So either there is a bug in newer libraqm versions, or they changed something deliberately what libgd needs to take into accont. This issue *might* be related to https://github.com/HOST-Oman/libraqm/pull/171, just from quickly skimming the changelog.

Thus, reopening as a reminder to look into this.

**Comment by lnw** [comment]
I've bisected what libraqm patch introduces this issue: That was 4de63. This has already been discussed and fixed in https://github.com/libgd/libgd/issues/790 . It is of course inconvenient that debian has updated libraqm to a version where the issue is introduced, but not libgd to the version where it's fixed, but that'll sort itself out some time, at least when libgd2.4 is released.

**Comment by cmb69** [comment]
Indeed, a new release is pending.

**Comment by oerdnj** [comment]
@cmb69 Hey, it would be useful to get libgd 2.4 out and packaged before next Debian freeze. Is that feasible or should I at least cherry-pick some patches into the Debian package?

**Comment by cmb69** [comment]
Well, I'm not really up-to-date regarding the current state of libgd, and tried a release a couple of years ago (2.2.5?), but that went bad (still not sure what I did wrong; but you fixed that).

Not sure who's active; maybe @vapier wants to roll a new release?

**Comment by pierrejoye** [comment]
is it still the case? libraqm advanced is not implemented correctly as I can see.  So if it is used, the bounding box will be wrong, as it lacks key details being required to get the actual correct values, even more for LTR texts or more "complex" texts input. I did not notice the bug shown here tho', with or without libraqm, the rendering itself was correct. The bbox in our tests suite  is a similar case.

I am not sure when I can look at this, as libraqm is still maintained etc. And could be handy for many of non western languages and complex layout.

**Comment by pierrejoye** [comment]
Fixed RAQM implemenation, bump version required to 0.10.x

Please open a new issue if anything is still not working as expected using RAQM
